### ISSUE TITLE
Bash file for initial setup to run portal

### ISSUE THREAD

**Issue by vishrutkohli** [systers/portal#346] opened 2018-03-08 08:50 UTC
## Description
As a user, it would be easier to run just one file instead of a number of commands,
I want to  create a bash file which does all the relevant installations and setup,
so that It is easier for other developers.

### Update [Required]
- [ ] Add bash file for intial setup of the project.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
4-5 hours

**Comment by vigzmv** [comment] 2018-03-08 20:59
@vishrutkohli Can you please provide an example of this. (or python/django project currently doing this)

**Comment by sammy1997** [comment] 2018-03-09 05:48
@jaemu @vishrutkohli what's the status of this issue? I would like to work on this if approved and not being worked on by others

**Comment by vishrutkohli** [comment] 2018-03-10 11:04
I want to work on it but waiting for an approval

**Comment by yatna** [comment] 2018-03-16 07:38
This is definitely a good idea. How are you planning to set the dbname, username, password etc in a shell script ? Will it be prompted to the user to enter ?

**Comment by sa7i** [comment] 2018-05-20 13:46
This is a duplicate of # 384, hence closing this issue.

**Closed by sa7i** 2018-05-20 13:46 UTC
